# 1. Prepare GEX data

In [14]:
DROP_NULLS = True
DROP_LOUVEAU = True
SELECT_PRE_TREATMENT = True
SELECT_RNA_SEQ = False

## Some mappings

In [15]:
rna_seq_sources = ['Hugo et al.', 'Kwong et al.', 'Yan et al.']
q_pcr_sources = ['Louveau et al.']
micro_array_sources = ['Long et al.', 'Rizos et al.']

source_map = {
    'doi:10.1016/j.cell.2015.07.061': 'Hugo et al.',
    'doi:10.1172/JCI78954DS1': 'Kwong et al.',
    'doi:10.1158/1078-0432.CCR-18-0720': 'Yan et al.',
    'doi:10.3390/cancers11081203': 'Louveau et al.',
    'doi:10.1038/ncomms6694': 'Long et al.',
    'doi:10.1158/1078-0432.CCR-13-3122': 'Rizos et al.'
}

In [16]:
import polars as pl

gex = pl.read_csv("../dataset/original/gene_expressions.csv")
gex = gex.with_columns(pl.col('source').replace(source_map))
gex

shape: (8_641_391, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ creation_d ┆ patientID ┆ sample_id ┆ … ┆ descripti ┆ value     ┆ temporali ┆ source    │
│ ---     ┆ atetime    ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ty        ┆ ---       │
│ i64     ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│         ┆ str        ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 7.60798   ┆ pre       ┆ Louveau   │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ et al.    │
│         ┆ 03260      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 16.095204 ┆ pre       ┆ Louveau   │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ et al.    │
│         ┆ 03285      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 3       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 4.1515    ┆ pre       ┆ Louveau   │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ et al.    │
│         ┆ 03298      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 4       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 1.199885  ┆ pre       ┆ Louveau   │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ et al.    │
│         ┆ 03312      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 5.47246   ┆ pre       ┆ Louveau   │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ et al.    │
│         ┆ 03324      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8641387 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 0.019542  ┆ progressi ┆ Hugo et   │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ al.       │
│         ┆ 29746      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 8641388 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 4.04421   ┆ progressi ┆ Hugo et   │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ al.       │
│         ┆ 29757      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 8641389 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 85.7967   ┆ progressi ┆ Hugo et   │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ al.       │
│         ┆ 29768      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 8641390 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 5.759167  ┆ progressi ┆ Hugo et   │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ al.       │
│         ┆ 29778      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 8641391 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 8.64874   ┆ progressi ┆ Hugo et   │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ al.       │
│         ┆ 29788      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Select only 'pre-treatment', drop Louveau

In [17]:
if SELECT_PRE_TREATMENT == True:
    gex = gex.filter((pl.col('temporality') == 'pre treatment'))
if SELECT_RNA_SEQ == True:
    gex = gex.filter(pl.col('source').is_in(rna_seq_sources))
if DROP_LOUVEAU == True:
    gex = gex.filter(pl.col('source') != 'Louveau et al.')

## Drop useless features

In [18]:
gex = gex.drop(['id', 'creation_datetime', 'GeneID', 'description', 'temporality'])

## Sample is useless if patientID or HGNC is not given

In [19]:
gex.select(pl.all().null_count())

shape: (1, 5)
┌───────────┬───────────┬────────┬───────┬────────┐
│ patientID ┆ sample_id ┆ HGNC   ┆ value ┆ source │
│ ---       ┆ ---       ┆ ---    ┆ ---   ┆ ---    │
│ u32       ┆ u32       ┆ u32    ┆ u32   ┆ u32    │
╞═══════════╪═══════════╪════════╪═══════╪════════╡
│ 92181     ┆ 0         ┆ 207000 ┆ 0     ┆ 0      │
└───────────┴───────────┴────────┴───────┴────────┘

In [20]:
if DROP_NULLS == True:
    gex = gex.drop_nulls(subset=['patientID', 'HGNC'])
    gex.select(pl.all().null_count())
    
gex.select(pl.all().null_count())

shape: (1, 5)
┌───────────┬───────────┬──────┬───────┬────────┐
│ patientID ┆ sample_id ┆ HGNC ┆ value ┆ source │
│ ---       ┆ ---       ┆ ---  ┆ ---   ┆ ---    │
│ u32       ┆ u32       ┆ u32  ┆ u32   ┆ u32    │
╞═══════════╪═══════════╪══════╪═══════╪════════╡
│ 0         ┆ 0         ┆ 0    ┆ 0     ┆ 0      │
└───────────┴───────────┴──────┴───────┴────────┘

## Add Method column

In [21]:
gex = gex.with_columns(
    pl.when(pl.col('source').is_in(rna_seq_sources))
    .then(pl.lit('RNA-seq'))
    .when(pl.col('source').is_in(micro_array_sources))
    .then(pl.lit('micro-array'))
    .otherwise(pl.lit('qPCR'))
    .alias('Method')
)
gex

shape: (4_175_330, 6)
┌───────────┬───────────────┬─────────┬───────────┬─────────────┬─────────┐
│ patientID ┆ sample_id     ┆ HGNC    ┆ value     ┆ source      ┆ Method  │
│ ---       ┆ ---           ┆ ---     ┆ ---       ┆ ---         ┆ ---     │
│ str       ┆ str           ┆ str     ┆ f64       ┆ str         ┆ str     │
╞═══════════╪═══════════════╪═════════╪═══════════╪═════════════╪═════════╡
│ YR_5306   ┆ 03660445B     ┆ NAT2    ┆ 0.0       ┆ Yan et al.  ┆ RNA-seq │
│ YR_5306   ┆ 03660445B     ┆ ADA     ┆ 26.233973 ┆ Yan et al.  ┆ RNA-seq │
│ YR_5306   ┆ 03660445B     ┆ CDH2    ┆ 1.138609  ┆ Yan et al.  ┆ RNA-seq │
│ YR_5306   ┆ 03660445B     ┆ AKT3    ┆ 12.692677 ┆ Yan et al.  ┆ RNA-seq │
│ YR_5306   ┆ 03660445B     ┆ GAGE12F ┆ 0.0       ┆ Yan et al.  ┆ RNA-seq │
│ …         ┆ …             ┆ …       ┆ …         ┆ …           ┆ …       │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11A  ┆ 0.0625681 ┆ Hugo et al. ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11B  ┆ 5.74608   ┆ Hugo et al. ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYX     ┆ 45.907933 ┆ Hugo et al. ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZEF1   ┆ 3.015137  ┆ Hugo et al. ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZZ3    ┆ 10.684633 ┆ Hugo et al. ┆ RNA-seq │
└───────────┴───────────────┴─────────┴───────────┴─────────────┴─────────┘

## Remove duplicate (sample-gene) rows

In [22]:
dupes_pl = (
    gex
    .filter(pl.len().over(['HGNC', 'sample_id']) > 1)
    .sort(['HGNC', 'sample_id'])
)
print(dupes_pl)

shape: (21_042, 6)
┌───────────┬───────────┬────────┬───────┬──────────────┬─────────┐
│ patientID ┆ sample_id ┆ HGNC   ┆ value ┆ source       ┆ Method  │
│ ---       ┆ ---       ┆ ---    ┆ ---   ┆ ---          ┆ ---     │
│ str       ┆ str       ┆ str    ┆ f64   ┆ str          ┆ str     │
╞═══════════╪═══════════╪════════╪═══════╪══════════════╪═════════╡
│ KC_10     ┆ 10A       ┆ ACE    ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_10     ┆ 10A       ┆ ACE    ┆ 2.84  ┆ Kwong et al. ┆ RNA-seq │
│ KC_12     ┆ 12A       ┆ ACE    ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_12     ┆ 12A       ┆ ACE    ┆ 10.27 ┆ Kwong et al. ┆ RNA-seq │
│ KC_13     ┆ 13A       ┆ ACE    ┆ 18.67 ┆ Kwong et al. ┆ RNA-seq │
│ …         ┆ …         ┆ …      ┆ …     ┆ …            ┆ …       │
│ KC_7      ┆ 7A        ┆ mir-95 ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_7      ┆ 7A        ┆ mir-95 ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_9      ┆ 9A        ┆ mir-95 ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_9      ┆ 9A        ┆ mir-95 ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
│ KC_9      ┆ 9A        ┆ mir-95 ┆ 0.0   ┆ Kwong et al. ┆ RNA-seq │
└───────────┴───────────┴────────┴───────┴──────────────┴─────────┘

In [23]:
gex = gex.sort('value', descending=True).unique(subset=['HGNC', 'sample_id'], keep='first')

dupes_pl = (
    gex
    .filter(pl.len().over(['HGNC', 'sample_id']) > 1)
    .sort(['HGNC', 'sample_id'])
)
print(dupes_pl)

shape: (0, 6)
┌───────────┬───────────┬──────┬───────┬────────┬────────┐
│ patientID ┆ sample_id ┆ HGNC ┆ value ┆ source ┆ Method │
│ ---       ┆ ---       ┆ ---  ┆ ---   ┆ ---    ┆ ---    │
│ str       ┆ str       ┆ str  ┆ f64   ┆ str    ┆ str    │
╞═══════════╪═══════════╪══════╪═══════╪════════╪════════╡
└───────────┴───────────┴──────┴───────┴────────┴────────┘

## Save pre-processed GEX

In [24]:
print(gex)
gex.write_csv(f'../dataset/created/gex.csv')

shape: (4_162_394, 6)
┌────────────┬─────────────────┬──────────────┬───────────┬──────────────┬─────────────┐
│ patientID  ┆ sample_id       ┆ HGNC         ┆ value     ┆ source       ┆ Method      │
│ ---        ┆ ---             ┆ ---          ┆ ---       ┆ ---          ┆ ---         │
│ str        ┆ str             ┆ str          ┆ f64       ┆ str          ┆ str         │
╞════════════╪═════════════════╪══════════════╪═══════════╪══════════════╪═════════════╡
│ RL_WMD-021 ┆ 8755_035H PreB  ┆ KBTBD10      ┆ 23.37587  ┆ Rizos et al. ┆ micro-array │
│ HL_Shi-15  ┆ Pt1-baseline    ┆ PRKAG2       ┆ 1.74235   ┆ Hugo et al.  ┆ RNA-seq     │
│ LR_WMD-022 ┆ 08766 PreC_014G ┆ LOC100134318 ┆ -4.151606 ┆ Long et al.  ┆ micro-array │
│ YR_2148    ┆ 05320220B       ┆ MEF2C        ┆ 10.563233 ┆ Yan et al.   ┆ RNA-seq     │
│ YR_3708    ┆ 03660598B       ┆ COA8         ┆ 11.098728 ┆ Yan et al.   ┆ RNA-seq     │
│ …          ┆ …               ┆ …            ┆ …         ┆ …            ┆ …           │
│ YR_2337    ┆ 05320372C       ┆ MYO1D-DT     ┆ 0.0       ┆ Yan et al.   ┆ RNA-seq     │
│ YR_2207    ┆ 05320232B       ┆ LOC100506472 ┆ 0.043373  ┆ Yan et al.   ┆ RNA-seq     │
│ KC_15      ┆ 15A             ┆ ZNF736P2Y    ┆ 0.0       ┆ Kwong et al. ┆ RNA-seq     │
│ YR_2136    ┆ 05320243B       ┆ DAD1         ┆ 71.458999 ┆ Yan et al.   ┆ RNA-seq     │
│ LR_MTP-009 ┆ 28094 PreB      ┆ LOC100128435 ┆ 1.293019  ┆ Long et al.  ┆ micro-array │
└────────────┴─────────────────┴──────────────┴───────────┴──────────────┴─────────────┘

## Create GEX_MAT

In [25]:
gex_mat = gex.pivot(on='sample_id', index='HGNC', values='value')
gex_mat

shape: (51_465, 144)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HGNC      ┆ 8755_035H ┆ Pt1-basel ┆ 08766     ┆ … ┆ 05420129C ┆ Pt2-basel ┆ 05320205B ┆ 05320100 │
│ ---       ┆ PreB      ┆ ine       ┆ PreC_014G ┆   ┆ ---       ┆ ine       ┆ ---       ┆ B        │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ KBTBD10   ┆ 23.37587  ┆ null      ┆ 7.854737  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ PRKAG2    ┆ 26.15605  ┆ 1.74235   ┆ 57.46408  ┆ … ┆ 1.692718  ┆ 3.843775  ┆ 6.949114  ┆ 4.202007 │
│ LOC100134 ┆ 14.48026  ┆ null      ┆ -4.151606 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 318       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MEF2C     ┆ 69.05501  ┆ 3.237085  ┆ 207.1043  ┆ … ┆ 7.545793  ┆ 9.756905  ┆ 13.143111 ┆ 8.339831 │
│ COA8      ┆ null      ┆ null      ┆ null      ┆ … ┆ 7.780042  ┆ null      ┆ 8.42633   ┆ 15.36894 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SGOL1P2   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ HNRNPH1P2 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ GAPDHP70  ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ IGKJ4     ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ MIR4520A  ┆ null      ┆ 0.0       ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
gex_mat.write_csv(f'../dataset/created/gex_mat.csv')