# Merge Clinical + GEX

In [12]:
import pandas as pd
import numpy as np

In [13]:
gex = pd.read_csv('../dataset/created/gex.csv',)
gex

,patientID,sample_id,HGNC,value,source,Method
0,LR_SMU-020,46225 PreC,PTPN20B,9.396869,Long et al.,micro-array
1,KC_19,19A,LOC286189,0.000000,Kwong et al.,RNA-seq
2,LR_MTP-034,28518_ 085G PreC,BRF1,95.004070,Long et al.,micro-array
3,YR_2420,05320132B,USP45,5.097668,Yan et al.,RNA-seq
4,LR_MTP-009,27551 PreB,MDM4,43.710980,Long et al.,micro-array
...,...,...,...,...,...,...
4162389,YR_2220,05320216B,SLC19A2,33.555115,Yan et al.,RNA-seq
4162390,YR_2096,05320093C,FUNDC2P2,1.483256,Yan et al.,RNA-seq
4162391,YR_1154,04240151B,VWA1,0.335072,Yan et al.,RNA-seq
4162392,HL_Shi-26,Pt2-baseline,CHRNA2,0.003782,Hugo et al.,RNA-seq
4162393,KC_15,15A,PRRC2CP1,0.000000,Kwong et al.,RNA-seq

In [14]:
clinical = pd.read_csv(f"../dataset/created/clinical.csv", index_col='Unnamed: 0')
clinical = clinical.drop(['PFS_month', 'brain_metastasis'], axis=1)
clinical

,patientID,sex,age,AJCC_stage,M_stage,LDH,immunotherapy_treatment,pre_MAPKi_treatment,source,pfs_label,cobimetinib,dabrafenib,trametinib,vemurafenib,C195W,K601I,MND,V600E,V600K,V600R
0,BS_000,male,56,IV,NaN,normal,no,no,Blateau et al.,2,0,1,1,0,0,0,0,1,0,0
1,BS_001,male,86,IV,NaN,normal,no,no,Blateau et al.,2,0,1,0,0,0,0,0,1,0,0
2,BS_002,female,47,IV,NaN,normal,no,no,Blateau et al.,2,0,1,1,0,0,0,0,1,0,0
3,BS_003,female,50,IV,NaN,NaN,no,no,Blateau et al.,0,0,0,0,1,0,0,0,1,0,0
4,BS_004,female,47,IV,NaN,elevated,no,no,Blateau et al.,1,0,1,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,HL_Shi-40,male,47,IV,M1C,NaN,no,no,Hugo et al.,0,0,0,0,1,0,0,0,1,0,0
382,HL_Shi-41,male,39,IV,M1A,NaN,no,no,Hugo et al.,0,0,0,0,1,0,0,0,1,0,0
383,HL_Shi-42,male,84,IV,M1C,NaN,no,no,Hugo et al.,1,0,1,0,0,0,0,0,1,0,0
384,HL_Shi-43,female,41,IV,M1C,NaN,no,no,Hugo et al.,1,0,0,0,1,0,0,0,1,0,0
385,HL_Shi-44,male,83,IV,M1C,NaN,no,no,Hugo et al.,0,0,0,0,1,0,0,0,0,1,0

In [15]:
# There are DUPLICATED patientID (126 patients, 143 patients-samples)
gex_wide = gex.pivot_table(index=['patientID', 'sample_id'], columns='HGNC', values='value', aggfunc='mean')
gex_wide

,HGNC,7A5,A1BG,A1BG-AS1,A1CF,A26C3,A2BP1,A2LD1,A2M,A2M-AS1,A2ML1,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
patientID,sample_id,,,,,,,,,,,,,,,,,,,,,
HL_Shi-14,Pt15-baseline,NaN,4.194890,0.981249,0.003694,NaN,NaN,NaN,57.88290,0.369273,0.015522,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HL_Shi-15,Pt1-baseline,NaN,8.357535,2.648650,0.019940,NaN,NaN,NaN,68.91065,0.203056,0.184964,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HL_Shi-22,Pt5-baseline,NaN,12.442250,0.734388,0.000000,NaN,NaN,NaN,239.42500,1.056091,1.895395,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HL_Shi-23,Pt9-baseline,NaN,7.154420,1.023753,0.004563,NaN,NaN,NaN,118.44700,0.951323,0.005059,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HL_Shi-24,Pt8-baseline,NaN,9.517875,1.568550,0.002085,NaN,NaN,NaN,65.50485,0.997582,25.452050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YR_3708,03660598B,NaN,NaN,1.600817,0.008137,NaN,NaN,NaN,NaN,42.862157,0.238685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YR_5306,03660445B,NaN,NaN,1.260380,0.007064,NaN,NaN,NaN,NaN,17.578871,0.211784,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YR_5311,03660447B,NaN,NaN,1.969883,0.022326,NaN,NaN,NaN,NaN,3.225992,0.283971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YR_8902,03660502B,NaN,NaN,0.975187,0.010838,NaN,NaN,NaN,NaN,4.845440,0.249454,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YR_nan,03660501B,NaN,NaN,1.500948,0.050472,NaN,NaN,NaN,NaN,3.042721,22.275126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
clinical_gex = clinical.merge(gex_wide.reset_index(), on='patientID', how='inner')
clinical_gex

,patientID,sex,age,AJCC_stage,M_stage,LDH,immunotherapy_treatment,pre_MAPKi_treatment,source,pfs_label,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,YR_3053,male,26,IV,M1B,elevated,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,YR_3708,female,58,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YR_3705,male,45,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YR_1106,male,48,IIIC,NaN,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YR_1110,male,33,IV,M1C,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HL_Shi-35,male,61,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,HL_Shi-37,male,65,IV,M1A,NaN,no,no,Hugo et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,HL_Shi-38,male,51,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,HL_Shi-43,female,41,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,HL_Shi-44,male,83,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
clinical_gex.to_csv('../dataset/created/clinical_gex.csv')