# Prepare data for Batch Correction

In [1]:
import pandas as pd
import numpy as np

In [3]:
clinical_gex = pd.read_csv('../dataset/created/clinical_gex.csv', low_memory=False)

print(clinical_gex.shape)
clinical_gex.head()

(134, 51486)

,patientID,sex,age,AJCC_stage,M_stage,LDH,immunotherapy_treatment,pre_MAPKi_treatment,source,pfs_label,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,YR_3053,male,26,IV,M1B,elevated,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,YR_3708,female,58,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YR_3705,male,45,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YR_1106,male,48,IIIC,NaN,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YR_1110,male,33,IV,M1C,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
CLINICAL_COLS = ["patientID", "sample_id", "sex", "age", "AJCC_stage", "M_stage", "LDH",
                "immunotherapy_treatment", "pre_MAPKi_treatment",
                "source", "cobimetinib", "dabrafenib", "trametinib","vemurafenib", 
                "C195W", "K601I", "MND", "R558Q", "V600E", "V600K","V600R", "pfs_label"]
GEX_COLS = [c for c in clinical_gex.columns if c not in CLINICAL_COLS]

total_col = len(CLINICAL_COLS) + len(GEX_COLS)

print(f"Clinical + GEX: {len(CLINICAL_COLS)} + {len(GEX_COLS)} = {total_col}")

Clinical + GEX: 22 + 51465 = 51487

In [6]:
gex = clinical_gex.iloc[:, len(CLINICAL_COLS)-2:]

print(gex.shape)
gex.head()

(134, 51466)

,sample_id,7A5,A1BG,A1BG-AS1,A1CF,A26C3,A2BP1,A2LD1,A2M,A2M-AS1,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,03660555B,NaN,NaN,1.029729,0.013240,NaN,NaN,NaN,NaN,16.754174,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,03660598B,NaN,NaN,1.600817,0.008137,NaN,NaN,NaN,NaN,42.862157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03660602B,NaN,NaN,1.761795,0.013022,NaN,NaN,NaN,NaN,20.930385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04240076F,NaN,NaN,0.771063,0.009576,NaN,NaN,NaN,NaN,13.671007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04240106F,NaN,NaN,1.473717,0.001873,NaN,NaN,NaN,NaN,16.397558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
gex_mat = gex.set_index('sample_id').T

print(gex_mat.shape)
gex_mat.head()

(51465, 134)

sample_id,03660555B,03660598B,03660602B,04240076F,04240106F,04240120C,04240151B,05320003B,05320011B,05320012B,...,Pt1-baseline,Pt5-baseline,Pt9-baseline,Pt8-baseline,Pt2-baseline,Pt4-baseline,Pt10-baseline,Pt16-baseline,Pt17-baseline,Pt6-baseline
7A5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1BG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.357535,12.442250,7.154420,9.517875,6.608285,5.074610,14.78075,0.961217,3.040353,4.186100
A1BG-AS1,1.029729,1.600817,1.761795,0.771063,1.473717,1.065738,1.794694,1.595717,0.509797,0.243509,...,2.648650,0.734388,1.023753,1.568550,0.674266,0.653775,0.27106,0.100338,0.420437,0.512325
A1CF,0.013240,0.008137,0.013022,0.009576,0.001873,0.000000,0.008215,0.003275,0.003053,0.000000,...,0.019940,0.000000,0.004563,0.002085,0.001765,0.000000,0.00000,0.000000,0.002556,0.000000
A26C3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
sample_source = clinical_gex[['sample_id', 'source', 'patientID', 'pfs_label']]

print(sample_source.shape)
sample_source.head()

(134, 4)

   sample_id      source patientID  pfs_label
0  03660555B  Yan et al.   YR_3053          0
1  03660598B  Yan et al.   YR_3708          2
2  03660602B  Yan et al.   YR_3705          2
3  04240076F  Yan et al.   YR_1106          0
4  04240106F  Yan et al.   YR_1110          0

In [9]:
sample_source.to_csv(f"../dataset/created/sample_source.csv", index=False)
gex_mat.index.name = 'sample_id'
gex_mat.to_csv(f"../dataset/created/gex_mat.csv", index=True)