# Merge Clinical + corrected GEX data

In [13]:
import pandas as pd

In [14]:
gex_mat = pd.read_csv(f"../dataset/created/gex_mat_corrected_sig.csv").set_index('sample_id').T
gex_mat['sample_id'] = gex_mat.index
gex_mat

sample_id,A1CF,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,AADACL2,AADACL3,...,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3,sample_id
03660555B,4.138459,3.758236,4.017679,4.658356,4.247856,6.245828,5.335733,4.214320,3.955209,3.936784,...,5.617357,4.337030,4.612033,5.242983,4.123198,6.349613,8.033822,5.893420,6.084096,03660555B
03660598B,4.137993,3.777168,4.027309,4.580839,4.260825,6.199024,5.388041,4.217820,3.969139,3.937040,...,5.703050,4.349439,4.596562,5.203072,4.119455,6.458094,7.446058,5.900072,5.954324,03660598B
03660602B,4.138439,3.770566,4.027114,4.604026,4.288809,5.689093,5.113199,4.207595,3.953489,3.936784,...,5.575595,4.350375,4.598942,5.177397,4.138278,6.389688,8.020844,5.993636,6.315351,03660602B
04240076F,4.138124,3.804644,4.021132,4.812146,4.265590,5.479267,5.164264,4.215681,3.979470,3.936784,...,5.553361,4.359007,4.598855,5.157423,4.117902,6.340705,8.136934,5.980467,5.843359,04240076F
04240106F,4.137420,3.760150,4.105545,4.609952,4.250174,6.333961,5.097606,4.209575,3.970086,3.936784,...,5.449051,4.360282,4.628323,5.274224,4.116303,6.610374,7.406934,6.075595,6.335867,04240106F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pt4-baseline,4.123155,3.743475,4.094566,4.874935,4.257411,5.944079,5.317714,4.195391,3.995417,3.988637,...,5.936034,4.339073,4.585804,5.414642,4.142600,6.367734,8.865404,5.894952,6.047321,Pt4-baseline
Pt10-baseline,4.123155,4.760595,4.072950,4.890957,4.255281,6.328840,5.954274,4.237846,4.240535,3.955771,...,5.615052,4.302966,4.513393,5.131467,4.142027,6.247105,8.085056,5.942121,5.722888,Pt10-baseline
Pt16-baseline,4.123155,3.558025,4.076928,5.221561,4.253552,6.107351,5.176390,4.177912,3.888001,3.926858,...,4.804977,4.294938,4.574262,5.349515,4.140077,6.197731,7.926534,6.140731,5.831315,Pt16-baseline
Pt17-baseline,4.123389,3.559510,4.072950,4.454504,4.254744,5.697156,5.095748,4.186112,3.888001,3.926858,...,5.754859,4.453692,4.695357,5.082347,4.144160,6.519512,6.897964,5.745779,6.310382,Pt17-baseline
Pt6-baseline,4.123155,3.560056,4.072950,5.003039,4.254427,5.793633,5.048553,4.178855,3.888001,3.926858,...,6.082783,4.332855,4.572627,4.840744,4.138783,6.341232,8.653088,5.748995,6.145445,Pt6-baseline

In [15]:
clinical_gex = pd.read_csv(f"../dataset/created/clinical_gex.csv", index_col='Unnamed: 0')
clinical_gex

/var/folders/cy/vstztct90b90zhd8ssbmwpgh0000gn/T/ipykernel_55557/1644580541.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  clinical_gex = pd.read_csv(f"../dataset/created/clinical_gex.csv", index_col='Unnamed: 0')

,patientID,sex,age,AJCC_stage,M_stage,LDH,immunotherapy_treatment,pre_MAPKi_treatment,source,pfs_label,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,YR_3053,male,26,IV,M1B,elevated,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,YR_3708,female,58,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YR_3705,male,45,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YR_1106,male,48,IIIC,NaN,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YR_1110,male,33,IV,M1C,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HL_Shi-35,male,61,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,HL_Shi-37,male,65,IV,M1A,NaN,no,no,Hugo et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,HL_Shi-38,male,51,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,HL_Shi-43,female,41,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,HL_Shi-44,male,83,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
CLINICAL_COLS = ["patientID", "sex", "age", "AJCC_stage", "M_stage", "LDH", 'sample_id', 'pfs_label',
                "immunotherapy_treatment", "pre_MAPKi_treatment",
                "source", "cobimetinib", "dabrafenib", "trametinib","vemurafenib", 
                "C195W", "K601I", "MND", "V600E", "V600K","V600R"]
GEX_COLS = [c for c in clinical_gex.columns if c not in CLINICAL_COLS]

clinical_gex = clinical_gex[CLINICAL_COLS]

In [17]:
gex_mat_reset = gex_mat.reset_index()
clinical_gex_1 = clinical_gex.merge(gex_mat_reset, on='sample_id', how='inner')

clinical_gex_1

,patientID,sex,age,AJCC_stage,M_stage,LDH,sample_id,pfs_label,immunotherapy_treatment,pre_MAPKi_treatment,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,YR_3053,male,26,IV,M1B,elevated,03660555B,0,no,no,...,5.848178,5.617357,4.337030,4.612033,5.242983,4.123198,6.349613,8.033822,5.893420,6.084096
1,YR_3708,female,58,IV,M1A,normal,03660598B,2,no,no,...,5.960990,5.703050,4.349439,4.596562,5.203072,4.119455,6.458094,7.446058,5.900072,5.954324
2,YR_3705,male,45,IV,M1A,normal,03660602B,2,no,no,...,6.270929,5.575595,4.350375,4.598942,5.177397,4.138278,6.389688,8.020844,5.993636,6.315351
3,YR_1106,male,48,IIIC,NaN,normal,04240076F,0,no,no,...,5.746751,5.553361,4.359007,4.598855,5.157423,4.117902,6.340705,8.136934,5.980467,5.843359
4,YR_1110,male,33,IV,M1C,normal,04240106F,0,no,no,...,5.973635,5.449051,4.360282,4.628323,5.274224,4.116303,6.610374,7.406934,6.075595,6.335867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HL_Shi-35,male,61,IV,M1C,NaN,Pt4-baseline,1,no,no,...,6.226732,5.936034,4.339073,4.585804,5.414642,4.142600,6.367734,8.865404,5.894952,6.047321
130,HL_Shi-37,male,65,IV,M1A,NaN,Pt10-baseline,2,no,no,...,5.771429,5.615052,4.302966,4.513393,5.131467,4.142027,6.247105,8.085056,5.942121,5.722888
131,HL_Shi-38,male,51,IV,M1C,NaN,Pt16-baseline,0,no,no,...,6.017434,4.804977,4.294938,4.574262,5.349515,4.140077,6.197731,7.926534,6.140731,5.831315
132,HL_Shi-43,female,41,IV,M1C,NaN,Pt17-baseline,1,no,no,...,6.249129,5.754859,4.453692,4.695357,5.082347,4.144160,6.519512,6.897964,5.745779,6.310382
133,HL_Shi-44,male,83,IV,M1C,NaN,Pt6-baseline,0,no,no,...,6.046067,6.082783,4.332855,4.572627,4.840744,4.138783,6.341232,8.653088,5.748995,6.145445

In [18]:
clinical_gex_1.to_csv(f"../dataset/created/clinical_gex_corrected.csv", index=False)