In [1]:
import polars as pl

In [2]:
DATASET = 'gex_pre'

In [3]:
gex_mat = pl.read_csv(f'../dataset/created/gex_mat/{DATASET}.csv')
gex_mat

shape: (51_466, 164)
┌────────────┬────────────┬───────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ HGNC       ┆ 28067_028D ┆ 05320459B ┆ 8755_072F  ┆ … ┆ LMSAM_14 ┆ LMSAM_26 ┆ LMSAM_20 ┆ LMSAM_27 │
│ ---        ┆ PreB       ┆ ---       ┆ PreB       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ f64       ┆ ---        ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
│            ┆ f64        ┆           ┆ f64        ┆   ┆          ┆          ┆          ┆          │
╞════════════╪════════════╪═══════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ LOC652566  ┆ 15.03131   ┆ null      ┆ 1.800405   ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ CEBPZ      ┆ 651.4442   ┆ 37.231517 ┆ 373.984    ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ LOC1001332 ┆ -3.634422  ┆ null      ┆ 3.9389     ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ 80         ┆            ┆           ┆            ┆   ┆          ┆          ┆          ┆          │
│ SLC5A11    ┆ -3.81321   ┆ 0.247378  ┆ 9.058964   ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ SLC38A5    ┆ 23.1732    ┆ 0.259844  ┆ 61.95675   ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ …          ┆ …          ┆ …         ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ MYL6P3     ┆ null       ┆ null      ┆ null       ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ RNU7-47P   ┆ null       ┆ null      ┆ null       ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ RPS27P14   ┆ null       ┆ null      ┆ null       ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ mir-3136   ┆ null       ┆ null      ┆ null       ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ TTLL7-IT1  ┆ null       ┆ null      ┆ null       ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
└────────────┴────────────┴───────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [ ]:
gex = pl.read_csv(f"../dataset/created/gex/{DATASET}.csv")
gex

shape: (4_175_910, 6)
┌───────────┬───────────────┬────────┬───────────┬────────────────┬─────────┐
│ patientID ┆ sample_id     ┆ HGNC   ┆ value     ┆ source         ┆ Method  │
│ ---       ┆ ---           ┆ ---    ┆ ---       ┆ ---            ┆ ---     │
│ str       ┆ str           ┆ str    ┆ f64       ┆ str            ┆ str     │
╞═══════════╪═══════════════╪════════╪═══════════╪════════════════╪═════════╡
│ LM_1      ┆ LMSAM_1       ┆ BRAF   ┆ 7.60798   ┆ Louveau et al. ┆ qPCR    │
│ LM_1      ┆ LMSAM_1       ┆ RAF1   ┆ 16.095204 ┆ Louveau et al. ┆ qPCR    │
│ LM_1      ┆ LMSAM_1       ┆ ARAF   ┆ 4.1515    ┆ Louveau et al. ┆ qPCR    │
│ LM_1      ┆ LMSAM_1       ┆ PDGFRB ┆ 1.199885  ┆ Louveau et al. ┆ qPCR    │
│ LM_1      ┆ LMSAM_1       ┆ IGF1R  ┆ 5.47246   ┆ Louveau et al. ┆ qPCR    │
│ …         ┆ …             ┆ …      ┆ …         ┆ …              ┆ …       │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11A ┆ 0.0625681 ┆ Hugo et al.    ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11B ┆ 5.74608   ┆ Hugo et al.    ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYX    ┆ 45.907933 ┆ Hugo et al.    ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZEF1  ┆ 3.015137  ┆ Hugo et al.    ┆ RNA-seq │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZZ3   ┆ 10.684633 ┆ Hugo et al.    ┆ RNA-seq │
└───────────┴───────────────┴────────┴───────────┴────────────────┴─────────┘

In [6]:
sample_source = (
    gex
    .select(["sample_id", "source", 'patientID', 'Method'])
    .unique()
)
sample_source

shape: (163, 4)
┌───────────────┬────────────────┬────────────┬─────────────┐
│ sample_id     ┆ source         ┆ patientID  ┆ Method      │
│ ---           ┆ ---            ┆ ---        ┆ ---         │
│ str           ┆ str            ┆ str        ┆ str         │
╞═══════════════╪════════════════╪════════════╪═════════════╡
│ 30608 PreB    ┆ Rizos et al.   ┆ RL_MTP-099 ┆ micro-array │
│ Pt2-baseline  ┆ Hugo et al.    ┆ HL_Shi-26  ┆ RNA-seq     │
│ 19A           ┆ Kwong et al.   ┆ KC_19      ┆ RNA-seq     │
│ LMSAM_11      ┆ Louveau et al. ┆ LM_11      ┆ qPCR        │
│ 05320220B     ┆ Yan et al.     ┆ YR_2148    ┆ RNA-seq     │
│ …             ┆ …              ┆ …          ┆ …           │
│ 05420169C     ┆ Yan et al.     ┆ YR_104002  ┆ RNA-seq     │
│ 05320093C     ┆ Yan et al.     ┆ YR_2096    ┆ RNA-seq     │
│ Pt17-baseline ┆ Hugo et al.    ┆ HL_Shi-43  ┆ RNA-seq     │
│ 05320452B     ┆ Yan et al.     ┆ YR_2494    ┆ RNA-seq     │
│ 05320446B     ┆ Yan et al.     ┆ YR_2409    ┆ RNA-seq     │
└───────────────┴────────────────┴────────────┴─────────────┘

In [7]:
# # Reorder columns to match sample_source row order
# sample_order = sample_source["sample_id"].to_list()
# gex_mat_reordered = gex_mat.select(["HGNC"] + sample_order)

# gex_mat_reordered

# Get column order from gex_mat (excluding HGNC)
col_order = gex_mat.columns[1:]  # skip HGNC

# Reorder sample_source rows to match gex_mat column order
sample_source_reordered = (
    pl.DataFrame({"sample_id": col_order})
    .join(sample_source, on="sample_id", how="left")
)


sample_source_reordered

shape: (163, 4)
┌─────────────────┬────────────────┬────────────┬─────────────┐
│ sample_id       ┆ source         ┆ patientID  ┆ Method      │
│ ---             ┆ ---            ┆ ---        ┆ ---         │
│ str             ┆ str            ┆ str        ┆ str         │
╞═════════════════╪════════════════╪════════════╪═════════════╡
│ 28067_028D PreB ┆ Rizos et al.   ┆ RL_WMD-007 ┆ micro-array │
│ 05320459B       ┆ Yan et al.     ┆ YR_2417    ┆ RNA-seq     │
│ 8755_072F PreB  ┆ Rizos et al.   ┆ RL_WMD-021 ┆ micro-array │
│ 27473_010F PreB ┆ Rizos et al.   ┆ RL_WMD-039 ┆ micro-array │
│ 05420169C       ┆ Yan et al.     ┆ YR_104002  ┆ RNA-seq     │
│ …               ┆ …              ┆ …          ┆ …           │
│ LMSAM_6         ┆ Louveau et al. ┆ LM_6       ┆ qPCR        │
│ LMSAM_14        ┆ Louveau et al. ┆ LM_14      ┆ qPCR        │
│ LMSAM_26        ┆ Louveau et al. ┆ LM_26      ┆ qPCR        │
│ LMSAM_20        ┆ Louveau et al. ┆ LM_20      ┆ qPCR        │
│ LMSAM_27        ┆ Louveau et al. ┆ LM_27      ┆ qPCR        │
└─────────────────┴────────────────┴────────────┴─────────────┘

In [ ]:
# sample_source_reordered.write_csv(f"../dataset/created/sample_source/{DATASET}.csv")