In [20]:
import polars as pl

clinical = pl.read_csv(f"../dataset/created/clinical_filtered/clinical.csv")
clinical

shape: (417, 15)
┌─────┬───────────┬────────┬─────┬───┬──────────┬────────────────┬────────────────┬────────────────┐
│     ┆ patientID ┆ sex    ┆ age ┆ … ┆ BRAF_mut ┆ brain_metastas ┆ immunotherapy_ ┆ pre_MAPKi_trea │
│ --- ┆ ---       ┆ ---    ┆ --- ┆   ┆ ---      ┆ is             ┆ treatment      ┆ tment          │
│ i64 ┆ str       ┆ str    ┆ i64 ┆   ┆ str      ┆ ---            ┆ ---            ┆ ---            │
│     ┆           ┆        ┆     ┆   ┆          ┆ str            ┆ str            ┆ str            │
╞═════╪═══════════╪════════╪═════╪═══╪══════════╪════════════════╪════════════════╪════════════════╡
│ 0   ┆ BS_000    ┆ male   ┆ 56  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 1   ┆ BS_001    ┆ male   ┆ 86  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 2   ┆ BS_002    ┆ female ┆ 47  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 3   ┆ BS_003    ┆ female ┆ 50  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 4   ┆ BS_004    ┆ female ┆ 47  ┆ … ┆ V600K    ┆ no             ┆ no             ┆ no             │
│ …   ┆ …         ┆ …      ┆ …   ┆ … ┆ …        ┆ …              ┆ …              ┆ …              │
│ 412 ┆ HL_40     ┆ male   ┆ 47  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 413 ┆ HL_41     ┆ male   ┆ 39  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 414 ┆ HL_42     ┆ male   ┆ 84  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 415 ┆ HL_43     ┆ female ┆ 41  ┆ … ┆ V600E    ┆ no             ┆ no             ┆ no             │
│ 416 ┆ HL_44     ┆ male   ┆ 83  ┆ … ┆ V600K    ┆ no             ┆ no             ┆ no             │
└─────┴───────────┴────────┴─────┴───┴──────────┴────────────────┴────────────────┴────────────────┘

In [21]:
gex = pl.read_csv(f"../dataset/created/gex_corrected/gex_pre.csv")
gex

shape: (143, 13_196)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id  ┆ source     ┆ patientID  ┆ Method    ┆ … ┆ KIAA1586 ┆ CLIC5    ┆ HAUS6    ┆ MIRLET7D │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 28067_028D ┆ Rizos et   ┆ RL_WMD-007 ┆ micro-arr ┆ … ┆ 5.228025 ┆ 3.361714 ┆ 5.481637 ┆ 5.074056 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05320459B  ┆ Yan et al. ┆ YR_2417    ┆ RNA-seq   ┆ … ┆ 5.01107  ┆ 3.988136 ┆ 4.584268 ┆ 5.42861  │
│ 8755_072F  ┆ Rizos et   ┆ RL_WMD-021 ┆ micro-arr ┆ … ┆ 4.351472 ┆ 4.736087 ┆ 4.613592 ┆ 3.482295 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 27473_010F ┆ Rizos et   ┆ RL_WMD-039 ┆ micro-arr ┆ … ┆ 3.931674 ┆ 4.051061 ┆ 3.77515  ┆ 4.080538 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05420169C  ┆ Yan et al. ┆ YR_104002  ┆ RNA-seq   ┆ … ┆ 4.567486 ┆ 3.997787 ┆ 4.500672 ┆ 5.267851 │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 05320410C  ┆ Yan et al. ┆ YR_2390    ┆ RNA-seq   ┆ … ┆ 4.975712 ┆ 4.035869 ┆ 4.538475 ┆ 3.985953 │
│ 16A        ┆ Kwong et   ┆ KC_16      ┆ RNA-seq   ┆ … ┆ 4.915265 ┆ 3.984482 ┆ 4.688729 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 08766      ┆ Long et    ┆ LR_WMD-022 ┆ micro-arr ┆ … ┆ 5.870401 ┆ 3.98803  ┆ 5.339926 ┆ 4.355084 │
│ PreC_014G  ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05320328B  ┆ Yan et al. ┆ YR_2472    ┆ RNA-seq   ┆ … ┆ 4.895777 ┆ 3.980708 ┆ 4.713952 ┆ 4.035995 │
│ Pt10-basel ┆ Hugo et    ┆ HL_Shi-37  ┆ RNA-seq   ┆ … ┆ 4.567853 ┆ 3.97117  ┆ 4.282064 ┆ 4.590374 │
│ ine        ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [22]:
clinical_gex = clinical.join(gex, on='patientID', how='inner')[:, 1:]
clinical_gex

shape: (125, 13_209)
┌───────────┬────────┬─────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ patientID ┆ sex    ┆ age ┆ AJCC_stage ┆ … ┆ KIAA1586 ┆ CLIC5    ┆ HAUS6    ┆ MIRLET7D │
│ ---       ┆ ---    ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ str    ┆ i64 ┆ str        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════════╪════════╪═════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ YR_3053   ┆ male   ┆ 26  ┆ IV         ┆ … ┆ 4.600878 ┆ 3.988906 ┆ 4.463209 ┆ 4.004989 │
│ YR_3708   ┆ female ┆ 58  ┆ IV         ┆ … ┆ 4.659288 ┆ 3.988537 ┆ 4.603643 ┆ 4.324637 │
│ YR_3705   ┆ male   ┆ 45  ┆ IV         ┆ … ┆ 5.028254 ┆ 3.996558 ┆ 4.800874 ┆ 4.348986 │
│ YR_1106   ┆ male   ┆ 48  ┆ IIIC       ┆ … ┆ 4.623254 ┆ 3.996295 ┆ 4.441287 ┆ 4.777784 │
│ YR_1110   ┆ male   ┆ 33  ┆ IV         ┆ … ┆ 4.879302 ┆ 4.01135  ┆ 4.533517 ┆ 5.50048  │
│ …         ┆ …      ┆ …   ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ KC_19     ┆ male   ┆ 62  ┆ IV         ┆ … ┆ 4.67608  ┆ 3.966343 ┆ 4.413339 ┆ 4.590374 │
│ KC_22     ┆ male   ┆ 49  ┆ IV         ┆ … ┆ 5.185139 ┆ 4.032988 ┆ 4.879651 ┆ 4.590374 │
│ KC_24     ┆ female ┆ 68  ┆ IV         ┆ … ┆ 4.964024 ┆ 4.149259 ┆ 4.899236 ┆ 4.590374 │
│ KC_25     ┆ male   ┆ 72  ┆ IV         ┆ … ┆ 4.863169 ┆ 4.027474 ┆ 4.765802 ┆ 4.590374 │
│ KC_34     ┆ male   ┆ 33  ┆ IV         ┆ … ┆ 4.702776 ┆ 3.972096 ┆ 4.466821 ┆ 4.590374 │
└───────────┴────────┴─────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [23]:
clinical_gex.select(pl.all().null_count())

shape: (1, 13_209)
┌───────────┬─────┬─────┬────────────┬───┬──────────┬───────┬───────┬──────────┐
│ patientID ┆ sex ┆ age ┆ AJCC_stage ┆ … ┆ KIAA1586 ┆ CLIC5 ┆ HAUS6 ┆ MIRLET7D │
│ ---       ┆ --- ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---   ┆ ---   ┆ ---      │
│ u32       ┆ u32 ┆ u32 ┆ u32        ┆   ┆ u32      ┆ u32   ┆ u32   ┆ u32      │
╞═══════════╪═════╪═════╪════════════╪═══╪══════════╪═══════╪═══════╪══════════╡
│ 0         ┆ 0   ┆ 0   ┆ 0          ┆ … ┆ 0        ┆ 0     ┆ 0     ┆ 0        │
└───────────┴─────┴─────┴────────────┴───┴──────────┴───────┴───────┴──────────┘

In [24]:
clinical_gex.write_csv(f"../dataset/created/clinical_gex/clinical_gex.csv")