In [29]:
import polars as pl

In [30]:
# gex_mat = pl.read_csv("dataset/gene_expressions_matrix.csv")
gex_mat = pl.read_csv('../dataset/created/gex_mat_rna_seq.csv')
gex_mat

shape: (38_792, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HGNC      ┆ 05320459B ┆ 05320196B ┆ 05320234B ┆ … ┆ 05320220B ┆ 05420129C ┆ 05320302B ┆ 05320449 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ B        │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CYP4F24P  ┆ 0.050866  ┆ 0.0       ┆ 0.029555  ┆ … ┆ 0.006098  ┆ 0.018093  ┆ 0.0       ┆ 0.0      │
│ TEX11     ┆ 0.104033  ┆ 0.029169  ┆ 0.092995  ┆ … ┆ 0.047971  ┆ 0.014232  ┆ 0.094406  ┆ 3.296924 │
│ TBC1D9B   ┆ 15.704316 ┆ 12.590393 ┆ 18.593042 ┆ … ┆ 11.47279  ┆ 15.541999 ┆ 10.972489 ┆ 11.65171 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ PMCHL2    ┆ 0.0       ┆ 0.031077  ┆ 0.059447  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ PDK2      ┆ 6.696817  ┆ 9.88272   ┆ 6.020661  ┆ … ┆ 10.573252 ┆ 12.858917 ┆ 7.174111  ┆ 8.492962 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LOC101928 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 509       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LOC100129 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 636       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MT-TQ     ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ OR11K2P   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ IGHV1-69  ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
gex = pl.read_csv("../dataset/created/gex_rna_seq.csv")
gex

shape: (2_671_394, 5)
┌───────────┬───────────────┬─────────┬───────────┬─────────────┐
│ patientID ┆ sample_id     ┆ HGNC    ┆ value     ┆ source      │
│ ---       ┆ ---           ┆ ---     ┆ ---       ┆ ---         │
│ str       ┆ str           ┆ str     ┆ f64       ┆ str         │
╞═══════════╪═══════════════╪═════════╪═══════════╪═════════════╡
│ YR_5306   ┆ 03660445B     ┆ NAT2    ┆ 0.0       ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ ADA     ┆ 26.233973 ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ CDH2    ┆ 1.138609  ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ AKT3    ┆ 12.692677 ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ GAGE12F ┆ 0.0       ┆ Yan et al.  │
│ …         ┆ …             ┆ …       ┆ …         ┆ …           │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11A  ┆ 0.0625681 ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11B  ┆ 5.74608   ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYX     ┆ 45.907933 ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZEF1   ┆ 3.015137  ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZZ3    ┆ 10.684633 ┆ Hugo et al. │
└───────────┴───────────────┴─────────┴───────────┴─────────────┘

In [32]:
sample_source = (
    gex
    .select(["sample_id", "source"])
    .unique()
)
sample_source

shape: (95, 2)
┌──────────────┬──────────────┐
│ sample_id    ┆ source       │
│ ---          ┆ ---          │
│ str          ┆ str          │
╞══════════════╪══════════════╡
│ 05420211C    ┆ Yan et al.   │
│ 05320239B    ┆ Yan et al.   │
│ 24A          ┆ Kwong et al. │
│ 05420135C    ┆ Yan et al.   │
│ 05320436B    ┆ Yan et al.   │
│ …            ┆ …            │
│ Pt9-baseline ┆ Hugo et al.  │
│ Pt5-baseline ┆ Hugo et al.  │
│ 03660555B    ┆ Yan et al.   │
│ Pt4-baseline ┆ Hugo et al.  │
│ 05420099C    ┆ Yan et al.   │
└──────────────┴──────────────┘

In [33]:
# Reorder columns to match sample_source row order
sample_order = sample_source["sample_id"].to_list()
gex_mat_reordered = gex_mat.select(["HGNC"] + sample_order)

gex_mat_reordered

shape: (38_792, 96)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HGNC       ┆ 05420211C ┆ 05320239B ┆ 24A     ┆ … ┆ Pt5-basel ┆ 03660555B ┆ Pt4-basel ┆ 05420099C │
│ ---        ┆ ---       ┆ ---       ┆ ---     ┆   ┆ ine       ┆ ---       ┆ ine       ┆ ---       │
│ str        ┆ f64       ┆ f64       ┆ f64     ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│            ┆           ┆           ┆         ┆   ┆ f64       ┆           ┆ f64       ┆           │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CYP4F24P   ┆ 0.04164   ┆ 0.375076  ┆ null    ┆ … ┆ 0.009283  ┆ 0.026117  ┆ 0.115261  ┆ 0.0       │
│ TEX11      ┆ 0.076428  ┆ 0.01157   ┆ 0.2     ┆ … ┆ 0.0394765 ┆ 0.051361  ┆ 0.022525  ┆ 3.663622  │
│ TBC1D9B    ┆ 7.885541  ┆ 14.352998 ┆ 40.54   ┆ … ┆ 32.98105  ┆ 9.685787  ┆ 21.3921   ┆ 1.909076  │
│ PMCHL2     ┆ 0.0       ┆ 0.0       ┆ 0.02    ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ PDK2       ┆ 6.145159  ┆ 8.67572   ┆ 7.02    ┆ … ┆ 22.08965  ┆ 8.367973  ┆ 7.291475  ┆ 1.937967  │
│ …          ┆ …         ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ LOC1019285 ┆ null      ┆ null      ┆ 0.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 09         ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ LOC1001296 ┆ null      ┆ null      ┆ null    ┆ … ┆ 0.0       ┆ null      ┆ 0.013883  ┆ null      │
│ 36         ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ MT-TQ      ┆ null      ┆ null      ┆ 2.2     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ OR11K2P    ┆ null      ┆ null      ┆ 0.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ IGHV1-69   ┆ null      ┆ null      ┆ 1690.74 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [34]:
sample_source.write_csv("../dataset/created/sample_source_rna_seq.csv")