In [2]:
import polars as pl

In [3]:
# gex_mat = pl.read_csv("dataset/gene_expressions_matrix.csv")
gex_mat = pl.read_csv('../dataset/created/gex_mat_rna_seq.csv')
gex_mat

shape: (38_792, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HGNC      ┆ 05320459B ┆ 05320196B ┆ 05320234B ┆ … ┆ 05320220B ┆ 05420129C ┆ 05320302B ┆ 05320449 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ B        │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CYP4F24P  ┆ 0.050866  ┆ 0.0       ┆ 0.029555  ┆ … ┆ 0.006098  ┆ 0.018093  ┆ 0.0       ┆ 0.0      │
│ TEX11     ┆ 0.104033  ┆ 0.029169  ┆ 0.092995  ┆ … ┆ 0.047971  ┆ 0.014232  ┆ 0.094406  ┆ 3.296924 │
│ TBC1D9B   ┆ 15.704316 ┆ 12.590393 ┆ 18.593042 ┆ … ┆ 11.47279  ┆ 15.541999 ┆ 10.972489 ┆ 11.65171 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ PMCHL2    ┆ 0.0       ┆ 0.031077  ┆ 0.059447  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ PDK2      ┆ 6.696817  ┆ 9.88272   ┆ 6.020661  ┆ … ┆ 10.573252 ┆ 12.858917 ┆ 7.174111  ┆ 8.492962 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LOC101928 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 509       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ LOC100129 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 636       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MT-TQ     ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ OR11K2P   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ IGHV1-69  ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
sample_cols = [c for c in gex_mat.columns if c != "HGNC"]

# Cast only the String-typed sample columns to Float64
string_sample_cols = [c for c in sample_cols if gex_mat[c].dtype == pl.String]
print(f"String cols to fix: {string_sample_cols}")

gex_mat = gex_mat.with_columns(
    pl.col(string_sample_cols).cast(pl.Float64, strict=False)
)

# Verify
print(gex_mat.select(string_sample_cols).dtypes)

String cols to fix: []
[]

In [14]:
gex_mat_sort_by_var = (
    gex_mat.with_columns(
        pl.concat_list(sample_cols)
        .list.drop_nulls()
        .map_elements(lambda x: x.var(), return_dtype=pl.Float64)
        .alias("_variance")
    )
    .sort("_variance", descending=True)
    # .head(500)
    # .drop("_variance")
)
gex_mat_sort_by_var

shape: (51_465, 307)
┌─────────┬───────────┬───────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ HGNC    ┆ 03660196C ┆ 03660356C ┆ 03660445B ┆ … ┆ Pt9-DP1    ┆ Pt9-DP2   ┆ Pt9-basel ┆ _variance │
│ ---     ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---        ┆ ---       ┆ ine       ┆ ---       │
│ str     ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64        ┆ f64       ┆ ---       ┆ f64       │
│         ┆           ┆           ┆           ┆   ┆            ┆           ┆ f64       ┆           │
╞═════════╪═══════════╪═══════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ MIR6723 ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.540975e6 ┆ 4.03485e6 ┆ 5.006945e ┆ 1.4177e13 │
│         ┆           ┆           ┆           ┆   ┆            ┆           ┆ 6         ┆           │
│ MIR1204 ┆ 0.0       ┆ 0.0       ┆ 0.513703  ┆ … ┆ 0.0        ┆ 0.0       ┆ 176017.5  ┆ 7.4625e11 │
│ MIR4461 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 9.8204e10 │
│ MIR3687 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 2.9339e10 │
│ MIR663A ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 182705.0   ┆ 158203.0  ┆ 54178.0   ┆ 2.8743e10 │
│ …       ┆ …         ┆ …         ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ mir-942 ┆ null      ┆ null      ┆ null      ┆ … ┆ null       ┆ null      ┆ null      ┆ 0.0       │
│ mir-943 ┆ null      ┆ null      ┆ null      ┆ … ┆ null       ┆ null      ┆ null      ┆ 0.0       │
│ mir-944 ┆ null      ┆ null      ┆ null      ┆ … ┆ null       ┆ null      ┆ null      ┆ 0.0       │
│ mir-95  ┆ null      ┆ null      ┆ null      ┆ … ┆ null       ┆ null      ┆ null      ┆ 0.0       │
│ mir-96  ┆ null      ┆ null      ┆ null      ┆ … ┆ null       ┆ null      ┆ null      ┆ 0.0       │
└─────────┴───────────┴───────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [15]:
gex = pl.read_csv("dataset/gene_expressions.csv")
gex

shape: (8_641_391, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ creation_d ┆ patientID ┆ sample_id ┆ … ┆ descripti ┆ value     ┆ temporali ┆ source    │
│ ---     ┆ atetime    ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ty        ┆ ---       │
│ i64     ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│         ┆ str        ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 7.60798   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03260      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 2       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 16.095204 ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03285      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 3       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 4.1515    ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03298      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 4       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 1.199885  ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03312      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 5       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 5.47246   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03324      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8641387 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 0.019542  ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29746      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641388 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 4.04421   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29757      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641389 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 85.7967   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29768      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641390 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 5.759167  ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29778      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641391 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 8.64874   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29788      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
sample_source = (
    gex.select(["sample_id", "source"])
    .unique()
    # .filter(pl.col('source').is_in(['doi:10.1016/j.cell.2015.07.061', 'doi:10.1172/JCI78954DS1', 'doi:10.1158/1078-0432.CCR-18-0720']))
)
sample_source

shape: (305, 2)
┌──────────────────┬─────────────────────────────────┐
│ sample_id        ┆ source                          │
│ ---              ┆ ---                             │
│ str              ┆ str                             │
╞══════════════════╪═════════════════════════════════╡
│ 29232 ProgB      ┆ doi:10.1158/1078-0432.CCR-13-3… │
│ 22C              ┆ doi:10.1172/JCI78954DS1         │
│ Pt3-DP3          ┆ doi:10.1016/j.cell.2015.07.061  │
│ 31493_012D ProgB ┆ doi:10.1158/1078-0432.CCR-13-3… │
│ Pt3-DP1          ┆ doi:10.1016/j.cell.2015.07.061  │
│ …                ┆ …                               │
│ Pt8-DP2          ┆ doi:10.1016/j.cell.2015.07.061  │
│ 46897 PostB      ┆ doi:10.1158/1078-0432.CCR-13-3… │
│ 05320388B        ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ 28178_018A PreB  ┆ doi:10.1038/ncomms6694          │
│ 28765 ProgB      ┆ doi:10.1158/1078-0432.CCR-13-3… │
└──────────────────┴─────────────────────────────────┘

In [17]:
# Reorder columns to match sample_source row order
sample_order = sample_source["sample_id"].to_list()
gex_mat_reordered = gex_mat_sort_by_var.select(["HGNC"] + sample_order)

gex_mat_reordered

shape: (51_465, 306)
┌─────────┬─────────────┬──────┬────────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ HGNC    ┆ 29232 ProgB ┆ 22C  ┆ Pt3-DP3    ┆ … ┆ 46897      ┆ 05320388B ┆ 28178_018A ┆ 28765      │
│ ---     ┆ ---         ┆ ---  ┆ ---        ┆   ┆ PostB      ┆ ---       ┆ PreB       ┆ ProgB      │
│ str     ┆ f64         ┆ f64  ┆ f64        ┆   ┆ ---        ┆ f64       ┆ ---        ┆ ---        │
│         ┆             ┆      ┆            ┆   ┆ f64        ┆           ┆ f64        ┆ f64        │
╞═════════╪═════════════╪══════╪════════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ MIR6723 ┆ null        ┆ null ┆ 2.895885e6 ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ MIR1204 ┆ 4.633681    ┆ null ┆ 0.0        ┆ … ┆ 3.487287   ┆ 0.0       ┆ 7.035309   ┆ 18.67009   │
│ MIR4461 ┆ null        ┆ 0.07 ┆ 0.0        ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ MIR3687 ┆ null        ┆ null ┆ 0.0        ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ MIR663A ┆ null        ┆ null ┆ 0.0        ┆ … ┆ null       ┆ 0.0       ┆ null       ┆ null       │
│ …       ┆ …           ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …          ┆ …          │
│ mir-942 ┆ null        ┆ 0.0  ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ mir-943 ┆ null        ┆ 0.0  ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ mir-944 ┆ null        ┆ 0.0  ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ mir-95  ┆ null        ┆ 0.0  ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
│ mir-96  ┆ null        ┆ 0.0  ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null       │
└─────────┴─────────────┴──────┴────────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [ ]:
gex_mat_reordered = gex_mat_reordered.head(500)
gex_mat_reordered

shape: (500, 306)
┌───────────┬────────────┬────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HGNC      ┆ 29232      ┆ 22C    ┆ Pt3-DP3    ┆ … ┆ 46897     ┆ 05320388B ┆ 28178_018 ┆ 28765     │
│ ---       ┆ ProgB      ┆ ---    ┆ ---        ┆   ┆ PostB     ┆ ---       ┆ A PreB    ┆ ProgB     │
│ str       ┆ ---        ┆ f64    ┆ f64        ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---       │
│           ┆ f64        ┆        ┆            ┆   ┆ f64       ┆           ┆ f64       ┆ f64       │
╞═══════════╪════════════╪════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ MIR6723   ┆ null       ┆ null   ┆ 2.895885e6 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ MIR1204   ┆ 4.633681   ┆ null   ┆ 0.0        ┆ … ┆ 3.487287  ┆ 0.0       ┆ 7.035309  ┆ 18.67009  │
│ MIR4461   ┆ null       ┆ 0.07   ┆ 0.0        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ MIR3687   ┆ null       ┆ null   ┆ 0.0        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ MIR663A   ┆ null       ┆ null   ┆ 0.0        ┆ … ┆ null      ┆ 0.0       ┆ null      ┆ null      │
│ …         ┆ …          ┆ …      ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ GAGE2B    ┆ 12129.8    ┆ null   ┆ 0.0        ┆ … ┆ 36.82396  ┆ 0.0       ┆ 5935.793  ┆ 10270.65  │
│ CATSPER2  ┆ 5156.733   ┆ 0.99   ┆ 1.742055   ┆ … ┆ 2465.939  ┆ 8.423843  ┆ 4302.654  ┆ 3354.141  │
│ LOC440595 ┆ 13305.36   ┆ null   ┆ null       ┆ … ┆ 11112.38  ┆ null      ┆ 13892.21  ┆ 13599.21  │
│ SPP1      ┆ 8206.085   ┆ 103.68 ┆ 1454.665   ┆ … ┆ 1286.265  ┆ 1199.0339 ┆ 940.1465  ┆ 3394.159  │
│           ┆            ┆        ┆            ┆   ┆           ┆ 6         ┆           ┆           │
│ HLA-DPA1  ┆ 413.0251   ┆ 300.62 ┆ 3.11358    ┆ … ┆ 2995.619  ┆ null      ┆ 5676.029  ┆ 1123.017  │
└───────────┴────────────┴────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
gex_mat_reordered.write_csv("dataset/gene_expressions_matrix_clean.csv")
sample_source.write_csv("dataset/sample_source.csv")