In [14]:
import pandas as pd

In [15]:
DATASET = 'gex_pre'

In [16]:
sample_source = pd.read_csv(f"../dataset/created/sample_source/{DATASET}.csv")
sample_source

           sample_id          source   patientID       Method
0    28067_028D PreB    Rizos et al.  RL_WMD-007  micro-array
1          05320459B      Yan et al.     YR_2417      RNA-seq
2     8755_072F PreB    Rizos et al.  RL_WMD-021  micro-array
3    27473_010F PreB    Rizos et al.  RL_WMD-039  micro-array
4          05420169C      Yan et al.   YR_104002      RNA-seq
..               ...             ...         ...          ...
158          LMSAM_6  Louveau et al.        LM_6         qPCR
159         LMSAM_14  Louveau et al.       LM_14         qPCR
160         LMSAM_26  Louveau et al.       LM_26         qPCR
161         LMSAM_20  Louveau et al.       LM_20         qPCR
162         LMSAM_27  Louveau et al.       LM_27         qPCR

[163 rows x 4 columns]

In [17]:
clinical_gex = pd.read_csv(f"../dataset/created/clinical_gex/clinical_gex_w_target.csv")
clinical_gex = clinical_gex[['patientID', 'pfs_label']]
clinical_gex

/var/folders/cy/vstztct90b90zhd8ssbmwpgh0000gn/T/ipykernel_30829/805533737.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  clinical_gex = pd.read_csv(f"../dataset/created/clinical_gex/clinical_gex_w_target.csv")

    patientID  pfs_label
0     YR_3053          0
1     YR_3708          2
2     YR_3705          2
3     YR_1106          0
4     YR_1110          0
..        ...        ...
120     KC_19          2
121     KC_22          0
122     KC_24          0
123     KC_25          0
124     KC_34          2

[125 rows x 2 columns]

In [20]:
clinical_gex[clinical_gex.duplicated('patientID', keep=False)].sort_values('patientID')

      patientID  pfs_label
102  LR_MTP-034          0
101  LR_MTP-034          0
108  LR_SMU-028          1
107  LR_SMU-028          1
109  LR_WMD-017          1
110  LR_WMD-017          1
98   LR_WMD-022          0
99   LR_WMD-022          0
76   RL_MTP-063          1
77   RL_MTP-063          1
89   RL_MTP-066          0
90   RL_MTP-066          0
81   RL_WMD-006          0
82   RL_WMD-006          0
85   RL_WMD-007          0
84   RL_WMD-007          0
93   RL_WMD-013          1
94   RL_WMD-013          1
79   RL_WMD-021          1
80   RL_WMD-021          1
75   RL_WMD-025          1
74   RL_WMD-025          1
86   RL_WMD-027          0
87   RL_WMD-027          0
69   RL_WMD-039          2
68   RL_WMD-039          2

In [18]:
ids_source = set(sample_source['patientID'])
ids_clinical = set(clinical_gex['patientID'])

overlap = ids_source & ids_clinical
only_source = ids_source - ids_clinical
only_clinical = ids_clinical - ids_source

print(f"sample_source patients:  {len(ids_source)}")
print(f"clinical_gex patients:   {len(ids_clinical)}")
print(f"Overlap:                 {len(overlap)}")
print(f"Only in sample_source:   {len(only_source)}")
print(f"Only in clinical_gex:    {len(only_clinical)}")

sample_source patients:  146
clinical_gex patients:   112
Overlap:                 112
Only in sample_source:   34
Only in clinical_gex:    0

In [19]:
merged = sample_source.merge(clinical_gex, how='outer', on='patientID')
merged

         sample_id       source  patientID   Method  pfs_label
0    Pt15-baseline  Hugo et al.  HL_Shi-14  RNA-seq        NaN
1     Pt1-baseline  Hugo et al.  HL_Shi-15  RNA-seq        NaN
2     Pt5-baseline  Hugo et al.  HL_Shi-22  RNA-seq        NaN
3     Pt9-baseline  Hugo et al.  HL_Shi-23  RNA-seq        NaN
4     Pt8-baseline  Hugo et al.  HL_Shi-24  RNA-seq        NaN
..             ...          ...        ...      ...        ...
184      03660598B   Yan et al.    YR_3708  RNA-seq        2.0
185      03660445B   Yan et al.    YR_5306  RNA-seq        2.0
186      03660447B   Yan et al.    YR_5311  RNA-seq        0.0
187      03660502B   Yan et al.    YR_8902  RNA-seq        0.0
188      03660501B   Yan et al.     YR_nan  RNA-seq        NaN

[189 rows x 5 columns]